server:
  port: 7503
eureka: 
  client:
    register-with-eureka: false
    serviceUrl: 
      defaultZone: http://localhost:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddr}:${server.port}