server:
  port: 7200
spring:
  cloud:
    config:
      enabled: true
      server:
        svn:
          uri: https://user-20161118uc/svn/jenkinsRepositories/springcCoud/zmph-shop-parent/app-global-config-svn
          username: huangjian
          password: 123456
        #git:
        #  uri: https://github.com/pcf-guides/configuration-server-config-repo
        default-label: config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/ 
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#本地环境无需配置，只需启动mq
rabbitmq: 
  host: localhost
  port: 5672
  username: guest
  password: guest
