spring:
  application:
    name: config-server
  #读取gitbub配置文件
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/blue19demon/spring-cloud
          username: blue19demon
          password: 18076575691abcd
          search-paths: /**





server:
  port: 7200
#读取本地配置文件
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/ 
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    
spring:
  cloud:
    config:
      server: 
        native:
          search-locations: file:F:/softs/codes/springcCoud/zmph-shop-parent/properties # classpath:properties/搜索src/main/resource 下的properties文件夹下的文件
    #自动刷新
    bus:
      refresh:
        enabled: true
  profiles:
    active: native  # 配置使用本地储存
    
#本地环境无需配置，只需启动mq
rabbitmq: 
  host: localhost
  port: 5672
  username: guest
  password: guest
 
#进行暴露服务
management:
  endpoints:
    web:
      exposure:
        include: "*"
  