spring:
  profiles:
    active: '@spring.profiles.active@'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
    serialization:
      indent-output: true
    time-zone: GMT+8
    
disconf:
  app: disconf_demo
  conf_server_host: 127.0.0.1:8088
  conf_server_url_retry_sleep_seconds: 1
  conf_server_url_retry_times: 1
  enable:
    remote:
      conf: true
  #env: dev 这个配置随着 profiles。active 动态修改,详情见com.tgb.configs.DisconfConfig
  ignore: ''
  user_define_download_dir: ./config
  version: '1_0_0_0'
  